# Generated by Django 4.2.3 on 2023-08-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNumber', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Mourtuary', 'Mourtuary'), ('Basic', 'Basic'), ('Advance', 'Advance')], max_length=100)),
                ('evoc', models.FileField(upload_to='')),
                ('liscance', models.FileField(upload_to='')),
                ('aadhar', models.FileField(upload_to='')),
                ('busy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
