# Generated by Django 4.2.3 on 2023-08-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
