# Generated by Django 4.2.3 on 2023-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_driver_user_driver_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleatId', models.IntegerField(null=True, unique=True)),
                ('regNumber', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Mourtuary', 'Mourtuary'), ('Basic', 'Basic'), ('Advance', 'Advance')], max_length=100)),
                ('evoc', models.FileField(upload_to='')),
                ('liscance', models.FileField(upload_to='')),
                ('aadhar', models.FileField(upload_to='')),
                ('busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FleatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
