# Generated by Django 4.2.3 on 2023-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambulance_fleatowner_alter_driver_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='fleatId',
            field=models.IntegerField(null=True),
        ),
    ]
