# Generated by Django 4.2.3 on 2023-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ambulance_fleatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='first',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fleatowner',
            name='first',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fleatowner',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
