# Generated by Django 4.2.3 on 2023-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driver_first_driver_phone_fleatowner_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='first',
        ),
        migrations.RemoveField(
            model_name='fleatowner',
            name='first',
        ),
        migrations.AddField(
            model_name='fleatowner',
            name='companyName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
