# Generated by Django 4.2.3 on 2023-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_driver_first_remove_fleatowner_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOfFleat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True, unique=True)),
                ('fleatOwnerId', models.IntegerField(null=True, unique=True)),
                ('ambulanceId', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
