# Generated by Django 4.2.3 on 2023-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_driveroffleat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveroffleat',
            name='ambulanceId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driveroffleat',
            name='fleatOwnerId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
